[package]
name = "digginggame"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
lazy_static = "1.5.0"
macroquad = "0.4.14"
noise = "0.9.0"
rand = "0.9.2"
rand_distr = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
